### ISSUE TITLE
performance regression if quantifier lower bound is 1

### ISSUE THREAD

**Issue by lopex** [k-takata/Onigmo#100]
Commit https://github.com/k-takata/Onigmo/commit/282338f88a8bf0807a7a1d21b06f78abe9de8fac seems to prevent setting exact and map info for cases like:

`/x+/ =~"aaaaaaaaaaaaaaaa"`

or 

`/[b-z]+/ =~"aaaaaaaaaaaaaaaa"`

resulting ten-fold performance  regression.

The reason is that the else clause in optitmize_node_left (quantifier case) which propagates exact/map info is not triggered.

The simplest fix seems to be to just remove the else clause.

**Comment by k-takata** [comment]
It seems that the commit 282338f88a8bf0807a7a1d21b06f78abe9de8fac doesn't improve the performance. I will revert it.
