### ISSUE TITLE
(?i) not works properly

### ISSUE THREAD

**Issue by tengattack** [k-takata/Onigmo#120]
`onig_search` failed to match such pattern:

pattern: `(?i) *(TOOKY)[ _\-]([^;/]+) ?(?:Build|;)`
cannot match `Mozilla/5.0 (Linux; Android 4.0.3; TOOKY A9PLUS Build/IML74K) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166 Mobile Safari/535.19`
but can match `Mozilla/5.0 (Linux; U; Android 2.3.4; Zh-tw; TOOKY A9 Build/GRJ22) AppleWebKit/533.1 (KHTML, Like Gecko) Version/4.0 Mobile Safari/533.1`

**Comment by tengattack** [comment]
BTW, I'm using `ONIG_ENCODING_UTF8` which cause this problem, and if I change to `ONIG_ENCODING_ASCII` there is no problem.

**Comment by k-takata** [comment]
I found that #113 was broken. I will make a fix.
