### ISSUE TITLE
Update Unicode Version from 7.0.0 to 8.0.0

### ISSUE THREAD

**Issue by duerst** [k-takata/Onigmo#59]
Unicode Version 8.0.0 came out in the middle of this year. Onigmo should be updated to Unicode Version 8.0.0. I already submitted a pull request (https://github.com/k-takata/Onigmo/pull/58) that implements this.

**Comment by k-takata** [comment]
Thank you for submitting the issue.
Already updated to 9.0.0 in `devel-6.0` branch. Closing.
