### ISSUE TITLE
Regexp matching with \p{Upper} and \p{Lower} for EUC-JP doesn’t work.

### ISSUE THREAD

**Issue by Jin-chan** [k-takata/Onigmo#60]
U+FF21 (Ａ, FULLWIDTH LATIN CAPITAL LETTER A) and U+00c0 (À, LATIN CAPITAL LETTER A WITH GRAVE) is `Uppercase_Letter` so it should match and return 0 in following cases but this returns 1.

```Ruby
ruby -e 'puts "\uFF21A".encode("EUC-JP") =~ Regexp.compile("\\\p{Upper}".encode("EUC-JP”))' # => 1
ruby -e 'puts "\u00C0A".encode("EUC-JP") =~ Regexp.compile("\\\p{Upper}".encode("EUC-JP"))' # => 1
```
This also happens in lower case matching.

```Ruby
ruby -e 'puts "\uFF41a".encode("EUC-JP") =~ Regexp.compile("\\\p{Lower}".encode("EUC-JP"))' ＃=> 1
```

In Unicode encoding it works as follows.

```Ruby
ruby -e 'puts "\uFF21A" =~ Regexp.compile("\\\p{Upper}")'  # => 0
```
Looks like EUC-JP `\p{Upper}` and `\p{Lower}` regex is limited to ASCII characters.

**Comment by k-takata** [comment]
https://bugs.ruby-lang.org/issues/11859#change-59185

> Ruby doesn't have case tables for non Unicode encodings.
> 
> And EUC-JP is legacy encoding, I don't think such encoding should be extended.

I have the same opinion. Closing.
