### ISSUE TITLE
Thread safety of onig_search and onig_match.

### ISSUE THREAD

**Issue by peterhuene** [k-takata/Onigmo#63]
Forgive me if I'm working from incorrect assumptions as I've just begun integrating Onigmo into one of my projects. My understanding is that these functions are intended to be thread-safe.

Looking at the implementation of these `onig_search` and `onig_match`, I notice the following code attempting some synchronization at the start:

``` C
#if defined(USE_RECOMPILE_API) && defined(USE_MULTI_THREAD_SYSTEM)
start:
THREAD_ATOMIC_START;
...
```

This seems to be part of a (perhaps defunct?) feature, hidden behind `USE_RECOMPILE_API` that isn't set anywhere, that would recompile the regular expression from within `onig_search` and `onig_match`, something that's obviously not thread safe and needs to be protected (although a global lock would kill throughput).

Given that there appears to be no other synchronization in use other than this (dead?) code, I thought I would try changing the functions to take `const regex_t*` instead of `regex_t*` to at least signal thread safety with respect to the regular expression struct.

[Here is a comparison of a commit that adds const where needed](https://github.com/k-takata/Onigmo/compare/master...peterhuene:thread-safety).

Well, that wasn't that bad of a change, but unfortunately it won't build because [set_bm_backward_skip is used to modify the int_map_backward field of regex_t](https://github.com/peterhuene/Onigmo/blob/51a3b9d1021a00b35705ff4371a64feae3150631/regexec.c#L3834).  At first glance, this does not appear to be a thread safe mutation of `regex_t` state.

Is that the case or is this not a problem?

**Comment by k-takata** [comment]
Sorry for the very late response.
Now I'm thinking that removing all `THREAD_*` macro and making Onigmo thread-safe as Oniguruma 6.0 did.

**Comment by k-takata** [comment]
Now the all `THREAD_*` macros are removed in `devel-6.0` branch.
`set_bm_backward_skip()` is also disabled now.

**Comment by peterhuene** [comment]
Thanks!
