### ISSUE TITLE
Missing const qualifier on syntax parameter of onig_new_without_alloc.

### ISSUE THREAD

**Issue by peterhuene** [k-takata/Onigmo#85]
The current (6.1.1) prototype for `onig_new_without_alloc` function is:

```c
int onig_new_without_alloc(OnigRegex, const OnigUChar* pattern, const OnigUChar* pattern_end, OnigOptionType option, OnigEncoding enc, OnigSyntaxType* syntax, OnigErrorInfo* einfo);
```

Note that the `syntax` argument is missing a `const` qualifier.

As a result, in C++, we're unable to directly use the `ONIG_SYNTAX_...` macros as an argument because they ultimately use declarations of `ONIG_EXTERN const OnigSyntaxType OnigSyntax...;` and the const-qualifier cannot be cast away without a `const_cast` in C++.

**Comment by peterhuene** [comment]
Thanks!

**Comment by k-takata** [comment]
Thank you for the report.
