### ISSUE TITLE
Directly including shift_jist.c from windows_31j.c isn't very nice and causes some issues

### ISSUE THREAD

**Issue by gamecreature** [k-takata/Onigmo#88]
When using CLANG c++11 and directly building the sources of onigmo into a project. 
The linker gets linkage errors because it somehow optimizes the c file includes.

Error: 
```
Undefined symbols for architecture x86_64:
  "_OnigEncodingShift_JIS", referenced from:
      _re_mbcinit in reggnu.o
      _reg_set_encoding in regposix.o
```

Solution is to:
- rename `enc/shift_jis.c` to  `enc/shift_jis.h` 
- create a new enc/shift_jis.c with the following content:
```c
#include "shift_jis.h"
```
- change `enc/windows_31j.c` the  included 'shift_jis.c' to 'shift_jis.h' 
```c
#define ENC_CP932
#include "shift_jis.h"

// .. etc. .
```

Would you please consider not to #include a '.c' file directly.
But include a '.h' file

(This is causing issues in our project  When somebody directly embeds our library https://github.com/edbee/edbee-lib in a c++11 project.
See issue: https://github.com/edbee/edbee-lib/issues/9)

REMARK: This is NOT the standard build-process. It doesn't involve calling the make-files. It a project that embeds the sources.

**Comment by k-takata** [comment]
Thank you for the report.
Please try the latest commit.

**Comment by gamecreature** [comment]
Thank you very much for your quick response.
This commit solves the issue!  😄 👍
