### ISSUE TITLE
Missing UTS 51 binary properties for Emoji

### ISSUE THREAD

**Issue by ticky** [k-takata/Onigmo#89]
[Unicode Technical Standard #51](http://www.unicode.org/reports/tr51/) introduces emoji properties and data, which Onigmo doesn’t yet support.

For instance, one would expect this emoji character-matching regex (borrowed from [Mathias Bynens’ blog](https://mathiasbynens.be/notes/es-unicode-property-escapes#emoji) to be valid, but at this point it is not;
```ruby
/\p{Emoji_Modifier_Base}\p{Emoji_Modifier}?|\p{Emoji_Presentation}|\p{Emoji}\uFE0F/
```

**Comment by nurse** [comment]
You can use `/(?:\p{Grapheme_Cluster_Break=E_Base}|\p{Grapheme_Cluster_Break=E_Base_GAZ})\p{Grapheme_Cluster_Break=Extend}*\p{Grapheme_Cluster_Break=E_Modifier}?(?:\p{Grapheme_Cluster_Break=ZWJ}(?:\p{Grapheme_Cluster_Break=Glue_After_Zwj}|\p{Grapheme_Cluster_Break=E_Base_GAZ}\p{Grapheme_Cluster_Break=Extend}*\p{Grapheme_Cluster_Break=E_Modifier}?))*/` as UTR#51's `emoji sequence`.

**Comment by ticky** [comment]
That regex is _not_ an equivalent to the regex I posted! It doesn’t correctly match characters which require U+FE0F to be displayed as emoji!
