### ISSUE TITLE
Is Copyight Date range in COPYING file correct given the use of later code from Oniguruma?

### ISSUE THREAD

**Issue by SlySven** [k-takata/Onigmo#95]
I.e. the lines in the `COPYING` file currently:
https://github.com/k-takata/Onigmo/blob/b6c0a6b81cb5c9f8899ab31c21f3c9534bc313d5/COPYING#L5
and
https://github.com/k-takata/Onigmo/blob/b6c0a6b81cb5c9f8899ab31c21f3c9534bc313d5/COPYING#L37

do not reflect the later content in `regversion.c`:
https://github.com/k-takata/Onigmo/blob/b6c0a6b81cb5c9f8899ab31c21f3c9534bc313d5/regversion.c#L5
https://github.com/k-takata/Onigmo/blob/b6c0a6b81cb5c9f8899ab31c21f3c9534bc313d5/regversion.c#L51
in `win32/onigmo.rc`:
https://github.com/k-takata/Onigmo/blob/b6c0a6b81cb5c9f8899ab31c21f3c9534bc313d5/win32/onigmo.rc#L76
and in `enc/mktable.c`:
https://github.com/k-takata/Onigmo/blob/b6c0a6b81cb5c9f8899ab31c21f3c9534bc313d5/enc/mktable.c#L5
and I was hoping that those lines in the `COPYING` file (and possibly `onigmo.h`) could be fixed (set to range `2002-2016` perhaps, if that is appropriate) to clear this small matter up. 😄

I regret if this sounds a bit _picky_ but I am working on a GPL Project that uses a component from a library that itself uses _Onigmo_ and I am checked that we correctly list the details of the non-GPLed code (that we _need to do so to comply with the various MIT/BSD licences terms_ as I understand it) 😇 and, having spotted this inconsistency would like to get it cleared up...

**Comment by k-takata** [comment]
I have updated the copyright information in #126 to reflect the latest status.

**Comment by SlySven** [comment]
Ah, just passing by and I think this issue can be closed off now - thanks.
